Repository DTStack/dt-sql-parser, pull requests merged in 2023-11, with the labels that each got.

#198 feat: add sideEffects field to trigger treeShaking
  package.json
Labels: enhancement

#201 pgsql: upgrade pgsql's syntax file and complete all syntax's test unit
  src/grammar/pgsql/PostgreSQLLexer.g4
  src/grammar/pgsql/PostgreSQLParser.g4
  src/lib/pgsql/PostgreSQLLexer.interp
  src/lib/pgsql/PostgreSQLLexer.tokens
  src/lib/pgsql/PostgreSQLLexer.ts
  src/lib/pgsql/PostgreSQLLexerBase.ts
  src/lib/pgsql/PostgreSQLParser.interp
  src/lib/pgsql/PostgreSQLParser.tokens
  src/lib/pgsql/PostgreSQLParser.ts
  src/lib/pgsql/PostgreSQLParserBase.ts
  src/lib/pgsql/PostgreSQLParserListener.ts
  src/lib/pgsql/PostgreSQLParserVisitor.ts
  test/parser/pgsql/fixtures/select.sql
  test/parser/pgsql/selectStatement.test.ts
  test/parser/pgsql/syntax.test.ts
  test/parser/pgsql/syntax/alterStatement.test.ts
  test/parser/pgsql/syntax/createStatement.test.ts
  test/parser/pgsql/syntax/deleteStatement.test.ts
  test/parser/pgsql/syntax/dropStatement.test.ts
  test/parser/pgsql/syntax/fixtures/alter.sql
  test/parser/pgsql/syntax/fixtures/create.sql
  test/parser/pgsql/syntax/fixtures/delete.sql
  test/parser/pgsql/syntax/fixtures/drop.sql
  test/parser/pgsql/syntax/fixtures/insert.sql
  test/parser/pgsql/syntax/fixtures/others.sql
  test/parser/pgsql/syntax/fixtures/select.sql
  test/parser/pgsql/syntax/fixtures/update.sql
  test/parser/pgsql/syntax/insertStatement.test.ts
  test/parser/pgsql/syntax/others.test.ts
  test/parser/pgsql/syntax/selectStatement.test.ts
  test/parser/pgsql/syntax/updateStatement.test.ts
Labels: enhancement

#212 feat: add column to syntaxContextType
  src/parser/common/basic-parser-types.ts
Labels: new features

#218 Feat column codeCompletion
  src/grammar/flinksql/FlinkSqlParser.g4
  src/grammar/hive/HiveSqlParser.g4
  src/grammar/spark/SparkSqlLexer.g4
  src/grammar/spark/SparkSqlParser.g4
  src/grammar/trinosql/TrinoSql.g4
  src/lib/flinksql/FlinkSqlLexer.ts
  src/lib/flinksql/FlinkSqlParser.interp
  src/lib/flinksql/FlinkSqlParser.ts
  src/lib/flinksql/FlinkSqlParserListener.ts
  src/lib/flinksql/FlinkSqlParserVisitor.ts
  src/lib/hive/HiveSqlParser.interp
  src/lib/hive/HiveSqlParser.ts
  src/lib/hive/HiveSqlParserListener.ts
  src/lib/hive/HiveSqlParserVisitor.ts
  src/lib/spark/SparkSqlLexer.interp
  src/lib/spark/SparkSqlLexer.tokens
  src/lib/spark/SparkSqlLexer.ts
  src/lib/spark/SparkSqlParser.interp
  src/lib/spark/SparkSqlParser.tokens
  src/lib/spark/SparkSqlParser.ts
  src/lib/spark/SparkSqlParserListener.ts
  src/lib/spark/SparkSqlParserVisitor.ts
  src/lib/trinosql/TrinoSql.interp
  src/lib/trinosql/TrinoSqlListener.ts
  src/lib/trinosql/TrinoSqlParser.ts
  src/lib/trinosql/TrinoSqlVisitor.ts
  src/parser/flinksql.ts
  src/parser/hive.ts
  src/parser/spark.ts
  src/parser/trinosql.ts
  test/parser/flinksql/suggestion/fixtures/syntaxSuggestion.sql
  test/parser/flinksql/suggestion/syntaxSuggestion.test.ts
  test/parser/hive/suggestion/fixtures/syntaxSuggestion.sql
  test/parser/hive/suggestion/syntaxSuggestion.test.ts
  test/parser/spark/suggestion/fixtures/syntaxSuggestion.sql
  test/parser/spark/suggestion/syntaxSuggestion.test.ts
  test/parser/trinosql/suggestion/fixtures/syntaxSuggestion.sql
  test/parser/trinosql/suggestion/syntaxSuggestion.test.ts
Labels: new features

#224 Upgrade/docs
  README-zh_CN.md
  README.md
  docs/Roadmap.md
  docs/Tutorials.md
  package.json
Labels: documentation
