Repository DTStack/dt-sql-parser, pull requests merged in 2025-05, with the labels that each got.

#416 fix(flink): #415 fix supporting json function's different type
  src/grammar/flink/FlinkSqlLexer.g4
  src/grammar/flink/FlinkSqlParser.g4
  src/lib/flink/FlinkSqlLexer.interp
  src/lib/flink/FlinkSqlLexer.ts
  src/lib/flink/FlinkSqlParser.interp
  src/lib/flink/FlinkSqlParser.tokens
  src/lib/flink/FlinkSqlParser.ts
  test/parser/flink/syntax/fixtures/insertFromSelectQueries.sql
Labels: bug, Next Version

#366 feat: unify variables in lexer
  src/grammar/flink/FlinkSqlLexer.g4
  src/grammar/impala/ImpalaSqlLexer.g4
  src/grammar/mysql/MySqlLexer.g4
  src/grammar/postgresql/PostgreSqlLexer.g4
  src/grammar/spark/SparkSqlLexer.g4
  src/grammar/trino/TrinoSql.g4
  src/lib/flink/FlinkSqlLexer.interp
  src/lib/flink/FlinkSqlLexer.tokens
  src/lib/flink/FlinkSqlLexer.ts
  src/lib/flink/FlinkSqlParser.interp
  src/lib/flink/FlinkSqlParser.tokens
  src/lib/flink/FlinkSqlParser.ts
  src/lib/impala/ImpalaSqlLexer.interp
  src/lib/impala/ImpalaSqlLexer.tokens
  src/lib/impala/ImpalaSqlLexer.ts
  src/lib/impala/ImpalaSqlParser.interp
  src/lib/impala/ImpalaSqlParser.tokens
  src/lib/impala/ImpalaSqlParser.ts
  src/lib/mysql/MySqlLexer.interp
  src/lib/mysql/MySqlLexer.tokens
  src/lib/mysql/MySqlLexer.ts
  src/lib/mysql/MySqlParser.interp
  src/lib/mysql/MySqlParser.tokens
  src/lib/mysql/MySqlParser.ts
  src/lib/postgresql/PostgreSqlLexer.interp
  src/lib/postgresql/PostgreSqlLexer.tokens
  src/lib/postgresql/PostgreSqlLexer.ts
  src/lib/postgresql/PostgreSqlParser.interp
  src/lib/postgresql/PostgreSqlParser.tokens
  src/lib/postgresql/PostgreSqlParser.ts
  src/lib/spark/SparkSqlLexer.interp
  src/lib/spark/SparkSqlLexer.tokens
  src/lib/spark/SparkSqlLexer.ts
  src/lib/spark/SparkSqlParser.interp
  src/lib/spark/SparkSqlParser.tokens
  src/lib/spark/SparkSqlParser.ts
  src/lib/trino/TrinoSql.interp
  src/lib/trino/TrinoSql.tokens
  src/lib/trino/TrinoSqlLexer.interp
  src/lib/trino/TrinoSqlLexer.tokens
  src/lib/trino/TrinoSqlLexer.ts
  src/lib/trino/TrinoSqlParser.ts
  src/parser/flink/flinkSemanticContextCollector.ts
  src/parser/impala/impalaSemanticContextCollector.ts
  src/parser/mysql/mysqlSemanticContextCollector.ts
  src/parser/postgresql/postgreSemanticContextCollector.ts
  src/parser/spark/sparkSemanticContextCollector.ts
  src/parser/trino/trinoSemanticContextCollector.ts
  test/common/basicSQL.test.ts
Labels: Next Version

#334 feat: complete after error syntax
  src/parser/common/basicSQL.ts
  src/parser/common/semanticContextCollector.ts
  test/parser/flink/suggestion/completeAfterSyntaxError.test.ts
  test/parser/hive/suggestion/completeAfterSyntaxError.test.ts
  test/parser/impala/suggestion/completeAfterSyntaxError.test.ts
  test/parser/mysql/suggestion/completeAfterSyntaxError.test.ts
  test/parser/postgresql/suggestion/completeAfterSyntaxError.test.ts
  test/parser/spark/suggestion/completeAfterSyntaxError.test.ts
  test/parser/trino/suggestion/completeAfterSyntaxError.test.ts
Labels: Next Version

#396 check spelling errors for all sql g4
  src/grammar/flink/FlinkSqlLexer.g4
  src/grammar/flink/FlinkSqlParser.g4
  src/grammar/hive/HiveSqlParser.g4
  src/grammar/impala/ImpalaSqlParser.g4
  src/grammar/mysql/MySqlParser.g4
  src/grammar/postgresql/PostgreSqlParser.g4
  src/grammar/spark/SparkSqlParser.g4
  src/grammar/trino/TrinoSql.g4
  src/lib/flink/FlinkSqlLexer.interp
  src/lib/flink/FlinkSqlLexer.tokens
  src/lib/flink/FlinkSqlLexer.ts
  src/lib/flink/FlinkSqlParser.interp
  src/lib/flink/FlinkSqlParser.tokens
  src/lib/flink/FlinkSqlParser.ts
  src/lib/flink/FlinkSqlParserListener.ts
  src/lib/flink/FlinkSqlParserVisitor.ts
  src/lib/hive/HiveSqlParser.interp
  src/lib/hive/HiveSqlParser.ts
  src/lib/hive/HiveSqlParserListener.ts
  src/lib/hive/HiveSqlParserVisitor.ts
  src/lib/impala/ImpalaSqlParser.interp
  src/lib/impala/ImpalaSqlParser.ts
  src/lib/impala/ImpalaSqlParserListener.ts
  src/lib/impala/ImpalaSqlParserVisitor.ts
  src/lib/mysql/MySqlParser.interp
  src/lib/mysql/MySqlParser.ts
  src/lib/mysql/MySqlParserListener.ts
  src/lib/mysql/MySqlParserVisitor.ts
  src/lib/postgresql/PostgreSqlParser.interp
  src/lib/postgresql/PostgreSqlParser.ts
  src/lib/postgresql/PostgreSqlParserListener.ts
  src/lib/postgresql/PostgreSqlParserVisitor.ts
  src/lib/spark/SparkSqlParser.interp
  src/lib/spark/SparkSqlParser.ts
  src/lib/spark/SparkSqlParserListener.ts
  src/lib/spark/SparkSqlParserVisitor.ts
  src/lib/trino/TrinoSql.interp
  src/lib/trino/TrinoSqlListener.ts
  src/lib/trino/TrinoSqlParser.ts
  src/lib/trino/TrinoSqlVisitor.ts
  src/parser/postgresql/index.ts
  src/parser/postgresql/postgreEntityCollector.ts
  src/parser/postgresql/postgreErrorListener.ts
  test/parser/postgresql/listener.test.ts
  test/parser/postgresql/visitor.test.ts
Labels: new features, Next Version

#411 feat: #410 optimize processCandidates tokenIndexOffset
  src/parser/common/basicSQL.ts
  src/parser/flink/index.ts
  src/parser/hive/index.ts
  src/parser/impala/index.ts
  src/parser/mysql/index.ts
  src/parser/postgresql/index.ts
  src/parser/spark/index.ts
  src/parser/trino/index.ts
  test/parser/flink/suggestion/multipleStatement.test.ts
  test/parser/flink/suggestion/syntaxSuggestion.test.ts
  test/parser/hive/suggestion/multipleStatement.test.ts
  test/parser/hive/suggestion/syntaxSuggestion.test.ts
  test/parser/impala/suggestion/multipleStatement.test.ts
  test/parser/impala/suggestion/syntaxSuggestion.test.ts
  test/parser/mysql/suggestion/multipleStatement.test.ts
  test/parser/mysql/suggestion/syntaxSuggestion.test.ts
  test/parser/postgresql/suggestion/multipleStatement.test.ts
  test/parser/postgresql/suggestion/suggestionWithEntity.test.ts
  test/parser/postgresql/suggestion/syntaxSuggestion.test.ts
  test/parser/spark/suggestion/multipleStatement.test.ts
  test/parser/spark/suggestion/syntaxSuggestion.test.ts
  test/parser/trino/suggestion/multipleStatement.test.ts
  test/parser/trino/suggestion/syntaxSuggestion.test.ts
Labels: Next Version
